version: "3"

services:
  postgres_container:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 15432:5432
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
  
volumes:
  postgres_data_container: